services:
  manager:
    image: ${IMAGE:-alpine}
    container_name: volman
    hostname: volman
    stop_grace_period: 0s
    command: tail -f /dev/null
    volumes:
      - ./scripts:/volman/scripts:ro
