services:
  volman:
    # docker compose run --rm volman [command]
    image: deanayalon/volman:python
    build: 
      platforms:
        - linux/amd64
        - linux/arm64/v8
      tags:
        - deanayalon/volman:python${IMG_VER:+-}$IMG_VER
        - ghcr.io/deanayalon/volman:python
        - ghcr.io/deanayalon/volman:python${IMG_VER:+-}$IMG_VER
    container_name: volman-controller
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file: .env

  sandbox:
    # docker compose run -i sandbox
    extends: volman
    entrypoint: bash
    container_name: volman-sandbox