services:
  volman:
    # docker compose run --rm volman [command]
    image: deanayalon/volman:python
    build: 
      platforms:
        - linux/amd64
        - linux/arm64/v8
    container_name: volman-controller
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  sandbox:
    # docker compose run -i sandbox
    extends: volman
    entrypoint: bash
    container_name: volman-sandbox