[tool.poetry]
name = "volman"
version = "0.1.0-2"
description = "Easy volume management for Docker"
authors = ["Dean Ayalon <deanayalon@me.com>"]
readme = "README.md"
license = "ISC"

[tool.poetry.scripts]
build = "volman.pyinstaller:install"

[tool.poetry.dependencies]
python = "^3.12"
docker = "^7.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
